"""Generic RSF data generation and array utilities."""

from .array_algebra import ArrayAlgebraError, linefit, linefit_rsf, match, match_rsf, matmult, matmult_rsf
from .array_math import ArrayMathError, add_rsf, clip_rsf, divide_rsf, multiply_rsf, normalize_rsf, scale_rsf, tpow_rsf
from .attr import attr_rsf, format_attr
from .byte import ByteScaleError, byte_rsf, byte_scale
from .cat import CatError, cat_arrays, cat_rsf
from .complex_tools import ComplexToolError, cmplx_rsf, imag_rsf, real_rsf, rtoc_rsf
from .cut import CutError, cut_rsf
from .dd import DDError, convert_dtype_rsf, convert_endian_rsf, copy_rsf
from .difference import DifferenceError, diff_rsf, difference_metric
from .file_ops import CopyResult, FileToolError, RemoveResult, copy_rsf_dataset, remove_rsf_dataset
from .header_mask import HeaderMaskError, header_cut_rsf, header_window_rsf
from .header_table import (
    HeaderTable,
    HeaderTableError,
    format_header_table_attr,
    header_attr_table,
    header_math_table,
    header_sort_table,
    header_table_attr,
    header_table_math,
    header_table_sort,
    headermath_rsf,
    headersort_rsf,
    read_header_table,
    write_header_table,
)
from .info import (
    DisfilError,
    disfil_array,
    disfil_rsf,
    format_header_values,
    format_info,
    get_header_value,
    get_header_values,
    info_rsf,
)
from .interleave import InterleaveError, interleave_rsf
from .laplac import LaplacError, laplac, laplac_rsf
from .linear_operator import (
    CallableLinearOperator,
    ConjugateGradientResult,
    DotTestResult,
    IdentityOperator,
    LinearOperator,
    LinearOperatorError,
    MatrixOperator,
    complex_conjgrad_solve,
    complex_conjugate_gradient,
    complex_conjugate_gradient_normal,
    complex_dot_test,
    conjgrad_solve,
    conjugate_gradient,
    conjugate_gradient_normal,
    dot_test,
    format_dot_test_result,
)
from .math import MathExpressionError, math_rsf, safe_eval_math
from .mask import MaskError, mask_rsf
from .noise import NoiseError, add_noise, noise, noise_rsf
from .pad import PadError, pad_rsf
from .put import PutHeaderError, put_header
from .reverse import ReverseError, reverse_rsf
from .remap import RemapError, remap1, remap1_rsf, spline, spline_rsf, t2warp, t2warp_rsf
from .rotate import RotateError, rotate_rsf
from .sampling import (
    SamplingError,
    bin_1d,
    bin_2d,
    bin_rsf,
    linear_resample,
    linear_rsf,
    max1,
    max1_rsf,
    slice_array,
    slice_rsf,
)
from .spike import spike
from .spray import SprayError, spray_rsf, tile_rsf
from .stats import StatError, StatResult, format_stat, max_rsf, min_rsf, minmax_rsf
from .otsu import OtsuError, otsu_rsf, otsu_threshold
from .transp import TransposeError, reshape_rsf, transpose_array, transpose_rsf
from .tclip import TClipError, tclip, tclip_rsf
from .unary import (
    UnaryMathError,
    abs_rsf,
    absolute,
    exp,
    exp_rsf,
    histogram,
    histogram_rsf,
    log,
    log_rsf,
    pow_rsf,
    power,
    quantile,
    quantile_rsf,
    sign,
    sign_rsf,
    sqrt,
    sqrt_rsf,
    unary_rsf,
)
from .window import WindowError, window, window_rsf

__all__ = [
    "MathExpressionError",
    "ArrayAlgebraError",
    "ArrayMathError",
    "ByteScaleError",
    "CutError",
    "InterleaveError",
    "LaplacError",
    "MaskError",
    "PadError",
    "PutHeaderError",
    "TransposeError",
    "WindowError",
    "SprayError",
    "CatError",
    "ComplexToolError",
    "DDError",
    "DifferenceError",
    "FileToolError",
    "HeaderMaskError",
    "HeaderTableError",
    "LinearOperatorError",
    "DisfilError",
    "NoiseError",
    "ReverseError",
    "RemapError",
    "RotateError",
    "SamplingError",
    "StatError",
    "OtsuError",
    "TClipError",
    "CopyResult",
    "RemoveResult",
    "StatResult",
    "HeaderTable",
    "CallableLinearOperator",
    "ConjugateGradientResult",
    "DotTestResult",
    "IdentityOperator",
    "LinearOperator",
    "MatrixOperator",
    "add_noise",
    "attr_rsf",
    "add_rsf",
    "byte_rsf",
    "byte_scale",
    "bin_1d",
    "bin_2d",
    "bin_rsf",
    "cat_arrays",
    "cat_rsf",
    "cmplx_rsf",
    "convert_dtype_rsf",
    "convert_endian_rsf",
    "copy_rsf",
    "copy_rsf_dataset",
    "complex_conjgrad_solve",
    "complex_conjugate_gradient",
    "complex_conjugate_gradient_normal",
    "complex_dot_test",
    "conjgrad_solve",
    "conjugate_gradient",
    "conjugate_gradient_normal",
    "cut_rsf",
    "disfil_array",
    "disfil_rsf",
    "diff_rsf",
    "difference_metric",
    "divide_rsf",
    "format_attr",
    "format_header_table_attr",
    "format_header_values",
    "format_info",
    "format_dot_test_result",
    "format_stat",
    "get_header_value",
    "get_header_values",
    "header_attr_table",
    "header_cut_rsf",
    "header_math_table",
    "header_sort_table",
    "header_table_attr",
    "header_table_math",
    "header_table_sort",
    "header_window_rsf",
    "headermath_rsf",
    "headersort_rsf",
    "imag_rsf",
    "info_rsf",
    "interleave_rsf",
    "laplac",
    "laplac_rsf",
    "linear_resample",
    "linear_rsf",
    "linefit",
    "linefit_rsf",
    "clip_rsf",
    "dot_test",
    "math_rsf",
    "match",
    "match_rsf",
    "matmult",
    "matmult_rsf",
    "mask_rsf",
    "max_rsf",
    "max1",
    "max1_rsf",
    "min_rsf",
    "minmax_rsf",
    "multiply_rsf",
    "noise",
    "noise_rsf",
    "otsu_rsf",
    "otsu_threshold",
    "pad_rsf",
    "put_header",
    "read_header_table",
    "real_rsf",
    "remove_rsf_dataset",
    "remap1",
    "remap1_rsf",
    "normalize_rsf",
    "reshape_rsf",
    "reverse_rsf",
    "rotate_rsf",
    "rtoc_rsf",
    "safe_eval_math",
    "scale_rsf",
    "slice_array",
    "slice_rsf",
    "spline",
    "spline_rsf",
    "spike",
    "spray_rsf",
    "t2warp",
    "t2warp_rsf",
    "tile_rsf",
    "transpose_array",
    "transpose_rsf",
    "tclip",
    "tclip_rsf",
    "tpow_rsf",
    "window",
    "window_rsf",
    "write_header_table",
    "UnaryMathError",
    "abs_rsf",
    "absolute",
    "exp",
    "exp_rsf",
    "histogram",
    "histogram_rsf",
    "log",
    "log_rsf",
    "pow_rsf",
    "power",
    "quantile",
    "quantile_rsf",
    "sign",
    "sign_rsf",
    "sqrt",
    "sqrt_rsf",
    "unary_rsf",
]
