"""Python-friendly Madagascar/RSF tools."""

__version__ = "0.1.0"

from .api import RSFData, read, write
from .core.axis import Axis
from .core.hypercube import Hypercube
from .core.params import MissingParameterError, ParameterParseError, RSFParams
from .generic.array_math import ArrayMathError, add_rsf, clip_rsf, divide_rsf, multiply_rsf, normalize_rsf, scale_rsf, tpow_rsf
from .generic.attr import attr_rsf
from .generic.cat import CatError, cat_arrays, cat_rsf
from .generic.dd import DDError, convert_dtype_rsf, convert_endian_rsf, copy_rsf
from .generic.difference import DifferenceError, diff_rsf, difference_metric
from .generic.file_ops import CopyResult, FileToolError, RemoveResult, copy_rsf_dataset, remove_rsf_dataset
from .generic.header_mask import HeaderMaskError, header_cut_rsf, header_window_rsf
from .generic.header_table import (
    HeaderTable,
    HeaderTableError,
    format_header_table_attr,
    header_attr_table,
    header_math_table,
    header_sort_table,
    header_table_attr,
    header_table_math,
    header_table_sort,
    headermath_rsf,
    headersort_rsf,
    read_header_table,
    write_header_table,
)
from .generic.info import info_rsf
from .generic.interleave import InterleaveError, interleave_rsf
from .generic.linear_operator import (
    CallableLinearOperator,
    ConjugateGradientResult,
    DotTestResult,
    IdentityOperator,
    LinearOperator,
    LinearOperatorError,
    MatrixOperator,
    complex_conjgrad_solve,
    complex_conjugate_gradient,
    complex_conjugate_gradient_normal,
    complex_dot_test,
    conjgrad_solve,
    conjugate_gradient,
    conjugate_gradient_normal,
    dot_test,
    format_dot_test_result,
)
from .generic.math import MathExpressionError, math_rsf, safe_eval_math
from .generic.pad import PadError, pad_rsf
from .generic.put import PutHeaderError, put_header
from .generic.rotate import RotateError, rotate_rsf
from .generic.sampling import (
    SamplingError,
    bin_1d,
    bin_2d,
    bin_rsf,
    linear_resample,
    linear_rsf,
    max1,
    max1_rsf,
    slice_array,
    slice_rsf,
)
from .generic.spike import spike
from .generic.spray import SprayError, spray_rsf, tile_rsf
from .generic.stats import StatError, StatResult, format_stat, max_rsf, min_rsf, minmax_rsf
from .generic.statistics import (
    StatisticsError,
    fillnan,
    fillnan_rsf,
    finite_mask,
    isnan_mask,
    isnan_rsf,
    mean,
    mean_rsf,
    median,
    median_rsf,
    range_rsf,
    range_stats,
    rms,
    rms_rsf,
    stat_rsf,
    std,
    std_rsf,
    var_rsf,
    variance,
)
from .generic.transp import TransposeError, reshape_rsf, transpose_array, transpose_rsf
from .generic.unary import (
    UnaryMathError,
    abs_rsf,
    absolute,
    exp,
    exp_rsf,
    histogram,
    histogram_rsf,
    log,
    log_rsf,
    pow_rsf,
    power,
    quantile,
    quantile_rsf,
    sign,
    sign_rsf,
    sqrt,
    sqrt_rsf,
    unary_rsf,
)
from .generic.window import WindowError, window, window_rsf
from .hybrid import (
    add_arrays_cpp,
    batch_xcorr_cpp,
    backend_name as hybrid_backend_name,
    cpp_available as hybrid_cpp_available,
    last_backend as hybrid_last_backend,
    last_xcorr_backend as hybrid_last_xcorr_backend,
    scale_array_cpp,
    xcorr_backend_name as hybrid_xcorr_backend_name,
)
from .imaging.kirchhoff import ImagingError, kirchhoff_time_migration, kirchhoff_time_migration_array
from .io.rsf import RSFArray, RSFHeader, read_header, read_rsf, write_header, write_rsf
from .io.segy import (
    SegyError,
    SegyHeaders,
    extract_trace_header_table,
    read_segy_headers,
    rsf_to_segy,
    segy_to_rsf,
)
from .modeling.acoustic2d import (
    Acoustic2DError,
    absorbing_boundary_simple,
    acoustic2d_forward,
    ricker_wavelet,
)
from .plot.graph import graph
from .plot.grey import grey
from .plot.wiggle import wiggle
from .seismic.agc import AGCError, agc_rsf
from .seismic.fk import FKError, fk_filter, fk_spectrum, make_fk_mask
from .seismic.gain import GainError, gain_rsf
from .seismic.mute import MuteError, mute_rsf, mutter, mutter_rsf
from .seismic.nmo import NMOError, inverse_nmo, nmo_correct
from .seismic.radon import (
    RadonError,
    inverse_linear_radon,
    inverse_parabolic_radon,
    linear_radon,
    parabolic_radon,
    radon_adjoint_array,
    radon_model_array,
)
from .seismic.semblance import SemblanceError, semblance_scan
from .seismic.stack import StackError, stack_along_axis, stack_rsf, stacks_rsf
from .signal.convolution import (
    ConvolutionError,
    autocorr,
    autocorr_rsf,
    cconv_rsf,
    circular_convolve,
    convolve,
    convolve_rsf,
    correlate_rsf,
    envcorr_rsf,
    envelope_correlation,
    fft_convolve,
    xcorr_rsf,
    xcorr_traces,
)
from .signal.calculus import (
    CalculusError,
    causal_integrate,
    causint_rsf,
    deriv,
    deriv_rsf,
    integral,
    integral_rsf,
)
from .signal.conditioning import ConditioningError, clip2, clip2_rsf, shift, shifts_rsf
from .signal.fft import FFTError, fft_axis_header_update, fft_rsf, ifft_rsf, irfft_rsf, rfft_rsf
from .signal.fir import (
    FIRFilterError,
    band_energy,
    bandenergy_rsf,
    filter_bank,
    filterbank_rsf,
    filtfilt_rsf,
    fir_filter,
    firfilter_rsf,
    firwin,
    firwin_rsf,
    freq_response,
    freqz_rsf,
    parse_frequency_bands,
    zero_phase_fir_filter,
)
from .signal.filter import FilterError, bandpass_rsf, highpass_rsf, lowpass_rsf, make_filter_taper
from .signal.preprocessing import (
    PreprocessingError,
    cosine_taper,
    costaper_rsf,
    envelope,
    envelope_rsf,
    spectra,
    spectra_rsf,
    threshold,
    threshold_rsf,
)
from .signal.qc import (
    SignalQCError,
    bandstop,
    bandstop_rsf,
    decimate,
    decimate_rsf,
    demean,
    demean_rsf,
    detrend,
    detrend_rsf,
    local_rms,
    localrms_rsf,
    notch,
    notch_rsf,
)
from .signal.spectral import (
    SpectralQCError,
    apply_window,
    coherence,
    coherence_rsf,
    csd,
    csd_rsf,
    frequency_attributes,
    freqattr_rsf,
    psd,
    psd_rsf,
    snr,
    snr_rsf,
    spectral_normalize,
    spectral_whiten,
    spectrogram,
    spectrogram_rsf,
    specnorm_rsf,
    transfer_function,
    transfer_rsf,
    welch_csd,
    welch_psd,
    welch_rsf,
    welchcsd_rsf,
    whiten_rsf,
    window_function,
    windowfunc_rsf,
)

__all__ = [
    "__version__",
    "Axis",
    "AGCError",
    "Acoustic2DError",
    "ArrayMathError",
    "CalculusError",
    "CatError",
    "ConvolutionError",
    "ConditioningError",
    "DDError",
    "DifferenceError",
    "FFTError",
    "FileToolError",
    "FIRFilterError",
    "FKError",
    "FilterError",
    "GainError",
    "Hypercube",
    "HeaderMaskError",
    "HeaderTableError",
    "ImagingError",
    "InterleaveError",
    "LinearOperatorError",
    "MathExpressionError",
    "MissingParameterError",
    "MuteError",
    "NMOError",
    "PadError",
    "ParameterParseError",
    "PreprocessingError",
    "PutHeaderError",
    "RSFData",
    "RSFParams",
    "RSFArray",
    "RSFHeader",
    "RadonError",
    "RotateError",
    "SamplingError",
    "SegyError",
    "SegyHeaders",
    "SemblanceError",
    "SignalQCError",
    "SpectralQCError",
    "SprayError",
    "StackError",
    "StatError",
    "TransposeError",
    "WindowError",
    "CopyResult",
    "HeaderTable",
    "CallableLinearOperator",
    "ConjugateGradientResult",
    "DotTestResult",
    "IdentityOperator",
    "LinearOperator",
    "MatrixOperator",
    "RemoveResult",
    "StatResult",
    "absorbing_boundary_simple",
    "attr_rsf",
    "add_rsf",
    "add_arrays_cpp",
    "acoustic2d_forward",
    "agc_rsf",
    "autocorr",
    "autocorr_rsf",
    "apply_window",
    "bandpass_rsf",
    "band_energy",
    "bandenergy_rsf",
    "bandstop",
    "bandstop_rsf",
    "batch_xcorr_cpp",
    "bin_1d",
    "bin_2d",
    "bin_rsf",
    "cat_arrays",
    "cat_rsf",
    "causal_integrate",
    "causint_rsf",
    "cconv_rsf",
    "circular_convolve",
    "clip2",
    "clip2_rsf",
    "convolve",
    "convolve_rsf",
    "correlate_rsf",
    "convert_dtype_rsf",
    "convert_endian_rsf",
    "copy_rsf",
    "copy_rsf_dataset",
    "clip_rsf",
    "cosine_taper",
    "costaper_rsf",
    "coherence",
    "coherence_rsf",
    "csd",
    "csd_rsf",
    "complex_conjgrad_solve",
    "complex_conjugate_gradient",
    "complex_conjugate_gradient_normal",
    "complex_dot_test",
    "conjgrad_solve",
    "conjugate_gradient",
    "conjugate_gradient_normal",
    "deriv",
    "deriv_rsf",
    "decimate",
    "decimate_rsf",
    "demean",
    "demean_rsf",
    "detrend",
    "detrend_rsf",
    "diff_rsf",
    "difference_metric",
    "divide_rsf",
    "envelope",
    "envelope_correlation",
    "envelope_rsf",
    "envcorr_rsf",
    "extract_trace_header_table",
    "format_header_table_attr",
    "format_dot_test_result",
    "format_stat",
    "gain_rsf",
    "graph",
    "grey",
    "hybrid_backend_name",
    "hybrid_cpp_available",
    "hybrid_last_backend",
    "hybrid_last_xcorr_backend",
    "hybrid_xcorr_backend_name",
    "dot_test",
    "fft_convolve",
    "fft_axis_header_update",
    "fft_rsf",
    "filter_bank",
    "filterbank_rsf",
    "filtfilt_rsf",
    "fir_filter",
    "firfilter_rsf",
    "firwin",
    "firwin_rsf",
    "freq_response",
    "freqz_rsf",
    "frequency_attributes",
    "freqattr_rsf",
    "fk_filter",
    "fk_spectrum",
    "highpass_rsf",
    "header_cut_rsf",
    "header_attr_table",
    "header_math_table",
    "header_sort_table",
    "header_table_attr",
    "header_table_math",
    "header_table_sort",
    "header_window_rsf",
    "headermath_rsf",
    "headersort_rsf",
    "ifft_rsf",
    "info_rsf",
    "interleave_rsf",
    "integral",
    "integral_rsf",
    "inverse_linear_radon",
    "inverse_nmo",
    "inverse_parabolic_radon",
    "irfft_rsf",
    "kirchhoff_time_migration",
    "kirchhoff_time_migration_array",
    "linear_resample",
    "linear_rsf",
    "linear_radon",
    "lowpass_rsf",
    "local_rms",
    "localrms_rsf",
    "make_filter_taper",
    "make_fk_mask",
    "notch",
    "notch_rsf",
    "parse_frequency_bands",
    "psd",
    "psd_rsf",
    "max_rsf",
    "max1",
    "max1_rsf",
    "read",
    "read_header",
    "read_header_table",
    "read_rsf",
    "read_segy_headers",
    "rfft_rsf",
    "math_rsf",
    "min_rsf",
    "minmax_rsf",
    "multiply_rsf",
    "mute_rsf",
    "mutter",
    "mutter_rsf",
    "nmo_correct",
    "normalize_rsf",
    "pad_rsf",
    "parabolic_radon",
    "put_header",
    "radon_adjoint_array",
    "radon_model_array",
    "remove_rsf_dataset",
    "reshape_rsf",
    "ricker_wavelet",
    "rotate_rsf",
    "rsf_to_segy",
    "safe_eval_math",
    "scale_rsf",
    "scale_array_cpp",
    "segy_to_rsf",
    "semblance_scan",
    "shift",
    "shifts_rsf",
    "snr",
    "snr_rsf",
    "slice_array",
    "slice_rsf",
    "spike",
    "spectra",
    "spectra_rsf",
    "spectral_normalize",
    "spectral_whiten",
    "spectrogram",
    "spectrogram_rsf",
    "specnorm_rsf",
    "stack_along_axis",
    "stack_rsf",
    "stacks_rsf",
    "spray_rsf",
    "threshold",
    "threshold_rsf",
    "tile_rsf",
    "transpose_array",
    "transpose_rsf",
    "tpow_rsf",
    "transfer_function",
    "transfer_rsf",
    "welch_csd",
    "welch_psd",
    "welch_rsf",
    "welchcsd_rsf",
    "whiten_rsf",
    "window",
    "window_rsf",
    "window_function",
    "windowfunc_rsf",
    "zero_phase_fir_filter",
    "wiggle",
    "write",
    "write_header",
    "write_header_table",
    "write_rsf",
    "xcorr_rsf",
    "xcorr_traces",
    "UnaryMathError",
    "abs_rsf",
    "absolute",
    "exp",
    "exp_rsf",
    "histogram",
    "histogram_rsf",
    "log",
    "log_rsf",
    "pow_rsf",
    "power",
    "quantile",
    "quantile_rsf",
    "sign",
    "sign_rsf",
    "sqrt",
    "sqrt_rsf",
    "unary_rsf",
    "StatisticsError",
    "fillnan",
    "fillnan_rsf",
    "finite_mask",
    "isnan_mask",
    "isnan_rsf",
    "mean",
    "mean_rsf",
    "median",
    "median_rsf",
    "range_rsf",
    "range_stats",
    "rms",
    "rms_rsf",
    "stat_rsf",
    "std",
    "std_rsf",
    "var_rsf",
    "variance",
]
